version: "0"

services:
  db:
    image: mongo:4.4
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"

  app:
    image: daniro46/myapp
    depends_on:
      - db
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=mongodb://db/mydatabase
